# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: client
generate:
  # std-http-server: true
  models: true
  client: true
output: gen_anthropic.go
